### ISSUE TITLE
Read logging configuration from conf file

### ISSUE THREAD

**Issue by MishraShivendra** [SergiusTheBest/plog#118]
I've been looking for a way to pass logging configuration through conf file. Is there a way to do this?
e.g. A conf file might look like:
```
LOG_LEVEL=INFO
MODE=CONSOLE or MODE=LOG_FILE
LOG_FILE=/var/log/dev.log

```
If not, can you please reassign this feature to me?

Thanks,
Shivendra

**Comment by SergiusTheBest** [comment]
Hi @MishraShivendra,

Thanks for your interest in this! I though about config files but there are many possible log configurations so they cannot be described by a simple config file. And doing complex config file will require a lot of code. Thus I left config file implementation for plog users. Also windows guys tend to use registry instead of config files.

So I'd prefer to keep things as is for now.

**Comment by MishraShivendra** [comment]
Okay. Thanks for the response.
