### ISSUE TITLE
Function argument for use with plog

### ISSUE THREAD

**Issue by vdweller84** [SergiusTheBest/plog#256]
Hello,

Suppose I make a function that does something like that:

```
	void ExitWithError(_some_argument_type_ message) {
		PLOGD << message;
		std::terminate();
	}

```

In order to use it like this:

`XEOS::ExitWithError("This is an Error message with code: " << errorcode);`

What should _some_argument_type_ be? I tried std::ostream and a few other types but his doesn't compile.

**Comment by SergiusTheBest** [comment]
Hi!

Unfortunately this syntax is not possible in C++. 

You can have: `XEOS::ExitWithError(SomeType() << "This is an Error message with code: " << errorcode);` but it's not user friendly.

You can write a helper class to make this work: `XEOS::ExitWithError() << "This is an Error message with code: " << errorcode);`.

Another option is to make a macro instead of a function. Then you can have: `XEOS_ExitWithError("This is an Error message with code: " << errorcode);`. This is a super easy to implement but there will be no namespace XEOS.

Also you can create a fatal appender that will call `std::terminate()` on a message with `fatal` severity. Then you can have: `PLOGF << "This is an Error message with code: " << errorcode;`. However it won't call `std::terminate()` if you disable the log or set the log severity to `none` (so `fatal` message will be ignored). So be careful with the log settings in such scenario.

Note: with the first 2 options you wouldn't know from where `ExitWithError` was called, so you loose important information.

**Comment by vdweller84** [comment]
Thanks for the reply. Macro it is!
