### ISSUE TITLE
How to use plog library in mac, its not working in mac for me

### ISSUE THREAD

**Issue by repl-shenoy-sukumaran** [SergiusTheBest/plog#276]
Hi,

We have use this library to generate log file, its working fine on Windows. (We are using node-gyp to create node executable)
But in mac the log files are not generating on mac (No error also on console). Do we need to do additional steps to to work.

Like should set `PLOG_ENABLE_WCHAR_INPUT=1` for mac?
Also to link iconv?

Syntax

```
#include <plog/Log.h>
#include "plog/Initializers/RollingFileInitializer.h"

plog::init(plog::debug, "ncollect_log.txt", 1000000, 5);
LOG_DEBUG << "blah";
```

**Comment by paule32** [comment]
Hello,
PLOG lib is generated with C++.
The intention is, to use it with C++.
mac OS use Objective C/Objective C++. This two (three) DSL are different each other.
So, you can not simply use C++ with Objective C++.

Then, it is not easy to create Software for mac OS with free Software.
Because Apple has a store, and all new Software have to round a Software Qualify Test before the Software comes to the Users.
This is a Apple Business decision, to make a Monopol, and hold crime Software away.

This makes the Hard- and Software very expensive.
But, you have a maximum of Security.

**Comment by SergiusTheBest** [comment]
@repl-shenoy-sukumaran It should work on macOS without any special configuration. iconv and PLOG_ENABLE_WCHAR_INPUT are required only if you're dealing with `wchat_t`. 

For troubleshooting you can check whether `std::cout << "test" << std::endl;` works. Also try `PLOG_DEBUG` (maybe `LOG_DEBUG` is conflicting with another macro).

**Comment by SergiusTheBest** [comment]
@paule32 C++ works almost on any platform including macOS. Also you can mix Objective C++ and C++, so it's not an issue.

**Comment by repl-shenoy-sukumaran** [comment]
When you run the app locally its working, 
When you install the app the logs files are not generating so i suspect its may be permission issue. will investigate further.

Thanks for your support

**Comment by SergiusTheBest** [comment]
@repl-shenoy-sukumaran Yes, it could be a permission issue. Try setting an absolute file path to the log file.
