### ISSUE TITLE
utf-8 and Windows

### ISSUE THREAD

**Issue by vglavnyy** [SergiusTheBest/plog#69]
I need to log utf-8 string, without "u8-to-wide-to-narrow" conversions under Windows.
LOG_DEBUG << u8"мир-пир";
What is the simplest way for this under Windows?

**Comment by SergiusTheBest** [comment]
I'll take a look at what can be done.

**Comment by danieldietsch** [comment]
Is there any progress on this -- or some plans?

**Comment by SergiusTheBest** [comment]
@danieldietsch Just to clarify: do you use `char8_t` or `char`?

**Comment by danieldietsch** [comment]
I basically threat the source files under windows as utf-8 with msvc and `/utf-8`. It would be nice if I could do 
```
PLOGN << "😀🦀";
```
and always get `😀🦀` in a Windows terminal.

**Comment by danieldietsch** [comment]
It seems that the unicode support for Windows is somewhat buggy. 
I use msvc with `/utf8` and `plog::ColorConsoleAppender` and try the following.
```
    PLOGN << u8"u8😀🦀";
    PLOGN << u"u😀🦀";
    PLOGN << U"U😀🦀";
    PLOGN << L"L😀🦀";
    PLOGN << "😀🦀";
```
Windows Terminal, cmd, chcp 437 (same with bash)
![image](https://user-images.githubusercontent.com/3883391/220956021-19bc3619-db0b-491c-94d8-fcb12d563691.png)
conhost, cmd, chcp 437 (somewhat expected because the font does not support unicode)
![image](https://user-images.githubusercontent.com/3883391/220956747-1e412f46-f8f6-40c3-bdf7-f19d7ddc61bb.png)

Now the same written to a file and displayed with vscode
Windows Terminal, cmd, chcp 437 (same with bash)
![image](https://user-images.githubusercontent.com/3883391/220957268-177324d2-7b29-4c9a-af25-f2dbce06f327.png)
conhost, cmd, chcp 437
![image](https://user-images.githubusercontent.com/3883391/220957806-67e45fda-c494-4c6d-b05d-3c8aa0389500.png)

Is there a way to write unicode characters consistently right now?

Background colors seem also broken in Windows Terminal:
![image](https://user-images.githubusercontent.com/3883391/220959402-5b28e16d-90db-41ef-a10f-d8dc6c1378d8.png)
conhost looks ok:
![image](https://user-images.githubusercontent.com/3883391/220959626-9d64c487-028e-48fa-805b-aaa0e79c5903.png)

**Comment by SergiusTheBest** [comment]
@danieldietsch The Windows way is to use `wchar_t` everywhere. How did write a log to the file?

**Comment by danieldietsch** [comment]
Just redirecting the output `CXX11.exe > out.log`

Using `wchar_t` everywhere does not make sense for multiplatform projects (or at least for us it does not). 

If we could simply choose which `codePage` is passed to `toNarrow` and used in `toWide` we could switch that to `kUTF8` and use `/utf8` during compilation; then even with Windows it would pass "😀🦀" as expected (*):

``` cpp
static plog::ColorConsoleAppender<plog::TxtFormatter> appender{};
    plog::init(plog::debug, &appender);


    PLOG_FATAL << "Fatal";
    PLOG_INFO << "Info";

    PLOGD << u8"u8😀🦀";
    PLOGD << u"u😀🦀";
    PLOGD << U"U😀🦀";
    PLOGD << L"L😀🦀";
    PLOGD << "😀🦀";
    PLOGD << PLOG_NSTR("PLOG_NSTR 😀🦀");
```
![image](https://user-images.githubusercontent.com/3883391/220977353-ac18d35d-4474-4455-829b-4045278fcc13.png)

But I just saw, a better way is probably https://github.com/SergiusTheBest/plog/issues/239

(*) except for the background color; for that one would probably need to switch to https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences and use the [SetConsoleMode](https://docs.microsoft.com/en-us/windows/console/setconsolemode) API with the ENABLE_VIRTUAL_TERMINAL_PROCESSING (0x0004) flag. But I am not sure.

**Comment by SergiusTheBest** [comment]
@danieldietsch I'm adding support for UTF8 everywhere. It will automatically detect `/utf8`.

**Comment by danieldietsch** [comment]
Cool, looking forward to it!

**Comment by SergiusTheBest** [comment]
@danieldietsch @vglavnyy Support for Utf8Everywhere and char8_t is merged to master.
